import { createFileRoute, Link } from "@tanstack/react-router";
import { CalendarDays, Clock3, QrCode, Users } from "lucide-react";
import { Button } from "../components/ui/button";
import { useSeatify } from "../lib/seatify-context";

export const Route = createFileRoute("/bookings")({ head: () => ({ meta: [{ title: "Bookings — Seatify" },{ name: "description", content: "See your upcoming Seatify cafe reservations." },{ property: "og:title", content: "Bookings — Seatify" },{ property: "og:description", content: "See your upcoming cafe reservations." },{ property: "og:type", content: "website" },{ name: "twitter:card", content: "summary_large_image" }] }), component: Bookings });

function Bookings() {
  const { reservation, cancelReservation } = useSeatify();
  if (!reservation) return <div className="mx-auto grid min-h-[65vh] max-w-md place-items-center px-5 text-center"><div><span className="mx-auto grid size-16 place-items-center rounded-full bg-secondary"><CalendarDays className="size-7 text-primary" /></span><h1 className="mt-6 font-display text-4xl font-semibold">No plans yet</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Reserve a seat and your upcoming study sessions will appear here.</p><Button asChild className="mt-7"><Link to="/explore">Find a cafe</Link></Button></div></div>;
  return <div className="mx-auto max-w-3xl px-5 py-10 lg:py-16"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">Upcoming session</p><h1 className="mt-2 font-display text-4xl font-semibold sm:text-5xl">Your booking</h1><article className="mt-8 overflow-hidden rounded-xl bg-primary text-primary-foreground shadow-xl"><div className="grid sm:grid-cols-[1fr_230px]"><div className="p-7 sm:p-9"><span className="inline-flex items-center gap-2 rounded-full bg-success/20 px-3 py-1.5 text-xs font-semibold"><span className="size-2 rounded-full bg-success" />Confirmed</span><h2 className="mt-5 font-display text-3xl font-semibold">{reservation.cafeName}</h2><p className="mt-2 text-sm opacity-70">Universitas Indonesia campus</p><div className="mt-8 grid grid-cols-3 gap-3 border-t border-primary-foreground/20 pt-6 text-sm"><div><CalendarDays className="mb-2 size-4 opacity-60" /><span className="opacity-60">Date</span><strong className="mt-1 block">{reservation.date}</strong></div><div><Clock3 className="mb-2 size-4 opacity-60" /><span className="opacity-60">Duration</span><strong className="mt-1 block">{reservation.duration} hours</strong></div><div><Users className="mb-2 size-4 opacity-60" /><span className="opacity-60">Guests</span><strong className="mt-1 block">{reservation.people}</strong></div></div></div><div className="grid place-items-center border-t border-dashed border-primary-foreground/25 bg-primary-foreground/5 p-7 sm:border-l sm:border-t-0"><div className="text-center"><div className="mx-auto grid size-32 place-items-center rounded-md bg-background text-primary"><QrCode className="size-24" /></div><p className="mt-3 font-mono text-xs font-semibold">{reservation.code}</p></div></div></div></article><div className="mt-5 flex justify-end"><Button variant="ghost" onClick={cancelReservation}>Cancel reservation</Button></div></div>;
}