import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight, BarChart3, Megaphone, PencilLine, Plus, TrendingUp, Users } from "lucide-react";
import { Button } from "../components/ui/button";

export const Route = createFileRoute("/partner")({ head: () => ({ meta: [
  { title: "Cafe Partner Studio — Seatify" }, { name: "description", content: "Manage cafe capacity, promotions, and customer insights with Seatify." },
  { property: "og:title", content: "Cafe Partner Studio — Seatify" }, { property: "og:description", content: "Manage cafe availability and promotions." },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: PartnerPage });

function PartnerPage() {
  return <div className="mx-auto max-w-7xl px-5 py-9 lg:px-8 lg:py-14"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">Partner studio · FEB Coffee Corner</p><h1 className="mt-2 font-display text-4xl font-semibold sm:text-5xl">Good afternoon, Maya.</h1><p className="mt-3 text-sm text-muted-foreground">Here’s how your cafe is flowing today.</p></div><Button><Plus className="size-4" /> Create promotion</Button></div>
    <div className="mt-10 grid gap-5 lg:grid-cols-[1.25fr_0.75fr]"><section className="rounded-lg border border-border bg-card p-6 lg:p-8"><div className="flex items-center justify-between"><div><p className="text-sm text-muted-foreground">Live occupancy</p><p className="mt-1 font-display text-4xl font-semibold">25 / 50</p></div><span className="rounded-full bg-accent px-3 py-1.5 text-xs font-semibold text-accent-foreground">Comfortable</span></div><div className="mt-8 flex h-52 items-end justify-between gap-3 border-b border-border px-2">{[{t:"8am",h:"25%"},{t:"10am",h:"40%"},{t:"12pm",h:"68%"},{t:"2pm",h:"85%"},{t:"4pm",h:"72%"},{t:"6pm",h:"60%"}].map(({t,h}) => <div key={t} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><div className="w-full max-w-12 rounded-t-sm bg-primary/80 transition-all hover:bg-primary" style={{height:h}} /><span className="text-[10px] text-muted-foreground">{t}</span></div>)}</div><div className="mt-6 grid grid-cols-3 divide-x divide-border text-center"><div><strong>40%</strong><p className="text-xs text-muted-foreground">Morning</p></div><div><strong>85%</strong><p className="text-xs text-muted-foreground">Afternoon</p></div><div><strong>60%</strong><p className="text-xs text-muted-foreground">Evening</p></div></div></section>
      <section className="rounded-lg bg-primary p-7 text-primary-foreground"><TrendingUp className="size-7 opacity-70" /><p className="mt-12 text-sm opacity-70">Weekly visits</p><p className="mt-1 font-display text-5xl font-semibold">1,284</p><p className="mt-3 text-sm text-success">↑ 14% from last week</p><div className="mt-10 border-t border-primary-foreground/20 pt-5"><p className="text-sm opacity-70">Peak time today</p><p className="mt-1 text-lg font-semibold">1:30 – 3:00 PM</p></div></section></div>
    <section className="mt-8"><h2 className="font-display text-3xl font-semibold">Manage your cafe</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[{i:PencilLine,t:"Update capacity",d:"Keep live seats accurate"},{i:Megaphone,t:"Create promotions",d:"Reach students nearby"},{i:BarChart3,t:"Customer insights",d:"Understand visit patterns"},{i:Users,t:"Promote cafe",d:"Grow your community"}].map(({i:Icon,t,d}) => <button key={t} className="group flex min-h-40 flex-col items-start rounded-lg border border-border bg-card p-5 text-left transition-all hover:-translate-y-1 hover:shadow-lg"><div className="flex w-full justify-between"><Icon className="size-5 text-primary" /><ArrowUpRight className="size-4 text-muted-foreground transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></div><h3 className="mt-auto font-display text-xl font-semibold">{t}</h3><p className="mt-1 text-xs text-muted-foreground">{d}</p></button>)}</div></section>
  </div>;
}